# env:
#   global:
#     - CC_TEST_REPORTER_ID=dfca2049404572d59463c55b1ca17af7b542b1b64d0d7f73f7f19dbadfbd26ff

language: node_js
node_js:
  - '10'

notifications:
  email:
    on_success: never
    on_failure: change

# cache:
#   directories:
#     - node_modules

# before_script:
#   - npm install -g yarn nyc coveralls
#   - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
#   - chmod +x ./cc-test-reporter
#   - ./cc-test-reporter before-build

# script:
#   - yarn build
#   - yarn test
#   - yarn test --coverage
#   - nyc --reporter=lcov yarn test

# after_script:
#   - yarn report-coverage
#   - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
